export enum actionTypes {
    ADD_NEW_TIMER_TO_TIMERS_LIST_ACTION = 'ADD_NEW_TIMER_TO_TIMERS_LIST_ACTION',
    SET_CONTINUE_PROPS_ACTION = 'SET_CONTINUE_PROPS_ACTION',
    SET_STOP_PROPS_ACTION = 'SET_STOP_PROPS_ACTION',
    REMOVE_TIMER_ACTION = 'REMOVE_TIMER_ACTION',
    CANCEL_TIMER_ACTION = 'CANCEL_TIMER_ACTION',
}